param(
  [string]$ApiBaseUrl = "http://localhost:8080/api/v1",
  [string]$Email = "host-demo@rentme.dev",
  [string]$Password = "demo1234"
)

$ErrorActionPreference = "Stop"

function Wait-HttpOk {
  param(
    [string]$Url,
    [int]$TimeoutSeconds = 60
  )

  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  while ((Get-Date) -lt $deadline) {
    try {
      Invoke-RestMethod -Method Get -Uri $Url -TimeoutSec 5 | Out-Null
      return
    } catch {
      Start-Sleep -Seconds 1
    }
  }
  throw "Timeout waiting for $Url"
}

function Invoke-ApiPostJson {
  param(
    [string]$Url,
    [object]$Body,
    [string]$Token = ""
  )

  $headers = @{}
  if ($Token) {
    $headers["Authorization"] = "Bearer $Token"
  }

  return Invoke-RestMethod `
    -Method Post `
    -Uri $Url `
    -Headers $headers `
    -ContentType "application/json" `
    -Body ($Body | ConvertTo-Json -Depth 20)
}

function New-ListingPayload {
  param(
    [string]$City,
    [string]$RentalTerm,
    [int]$Bedrooms,
    [double]$AreaSqM,
    [int]$RateRub
  )

  $isLong = $RentalTerm -eq "long_term"
  $minNights = if ($isLong) { 14 } else { 1 }
  $maxNights = if ($isLong) { 90 } else { 21 }

  return @{
    title = "Smoke pricing ($City/$RentalTerm)"
    description = "Generated by validate_ml_pricing.ps1"
    property_type = "apartment"
    address = @{
      line1 = "Smoke street 1"
      line2 = ""
      city = $City
      region = $City
      country = "RU"
      lat = 0
      lon = 0
    }
    amenities = @()
    house_rules = @()
    tags = @()
    highlights = @()
    thumbnail_url = ""
    cancellation_policy_id = "flexible"
    guests_limit = [Math]::Max(1, $Bedrooms + 1)
    min_nights = $minNights
    max_nights = $maxNights
    rate_rub = $RateRub
    rental_term = $RentalTerm
    travel_minutes = 20
    travel_mode = "car"
    bedrooms = $Bedrooms
    bathrooms = 1
    floor = 5
    floors_total = 12
    renovation_score = 7
    building_age_years = 15
    area_sq_m = $AreaSqM
    photos = @()
  }
}

$backendBaseUrl = $ApiBaseUrl.TrimEnd("/")
if ($backendBaseUrl.EndsWith("/api/v1")) {
  $backendBaseUrl = $backendBaseUrl.Substring(0, $backendBaseUrl.Length - "/api/v1".Length)
}

Wait-HttpOk -Url "$backendBaseUrl/readyz" -TimeoutSeconds 90
Wait-HttpOk -Url "http://localhost:8000/health" -TimeoutSeconds 90

$loginUrl = "$ApiBaseUrl/auth/login"
$login = Invoke-ApiPostJson -Url $loginUrl -Body @{ email = $Email; password = $Password }
if (-not $login.token) {
  throw "Login succeeded but token is empty"
}

$token = $login.token
$profiles = @(
  @{ name = "Москва short_term 1к 40м2"; city = "Moscow"; rental_term = "short_term"; bedrooms = 1; area_sq_m = 40; min_rub = 3000 },
  @{ name = "Москва short_term 3к 100м2"; city = "Moscow"; rental_term = "short_term"; bedrooms = 3; area_sq_m = 100; min_rub = 8000 },
  @{ name = "Краснодар short_term 1к 35м2"; city = "Krasnodar"; rental_term = "short_term"; bedrooms = 1; area_sq_m = 35; min_rub = 2000 },
  @{ name = "Москва long_term 1к 35м2"; city = "Moscow"; rental_term = "long_term"; bedrooms = 1; area_sq_m = 35; min_rub = 25000 },
  @{ name = "Москва long_term 3к 90м2"; city = "Moscow"; rental_term = "long_term"; bedrooms = 3; area_sq_m = 90; min_rub = 60000 }
)

$createUrl = "$ApiBaseUrl/host/listings"

$failed = 0
foreach ($p in $profiles) {
  $payload = New-ListingPayload -City $p.city -RentalTerm $p.rental_term -Bedrooms $p.bedrooms -AreaSqM $p.area_sq_m -RateRub 1
  $created = Invoke-ApiPostJson -Url $createUrl -Body $payload -Token $token
  $listingId = $created.id
  if (-not $listingId) {
    throw "Create listing failed: missing id"
  }

  $suggestUrl = "$ApiBaseUrl/host/listings/$listingId/price-suggestion"
  $suggest = Invoke-ApiPostJson -Url $suggestUrl -Body @{} -Token $token
  $recommended = [int64]($suggest.recommended_price_rub)

  if ($recommended -lt [int64]$p.min_rub) {
    Write-Host ("FAIL {0}: recommended={1} < min={2}" -f $p.name, $recommended, $p.min_rub)
    $failed++
  } else {
    Write-Host ("OK   {0}: recommended={1} >= min={2}" -f $p.name, $recommended, $p.min_rub)
  }
}

if ($failed -gt 0) {
  throw "Pricing validation failed: $failed profile(s)"
}

Write-Host "All profiles OK"
